### ISSUE TITLE
Similar project

### ISSUE THREAD

**Issue by kevee** [Hipo/university-domains-list#53]
Here's a list I've been maintaining for several years that uses the fact that Educause allows % wildcards in whois searches:

https://github.com/kevee/edudomains

**Comment by yigitguler** [comment]
Hi @kevee 

Nice package! We can crosscheck universities and fill missing ones. Is there a way to get the university name & country with your method?

**Comment by zakawat** [comment]
@kevee  the problem is that your data is contained in text file that only contains the domain names _(which alone isn't that much useful)_.
Here we also provide extra data _(like alpha_two_code, country, state-province , etc )_.
I think ours is far more better.
All of our data is managed in **JSON** file which awesome.
